TaiDuc1001/SWP391_Menstrual-Management

frontend/src/index.tsx

Add text in index.tsx

---

frontend/src/pages/Customer/MenstrualCycles.tsx

 Ms sửa nhe thây Đỗ Tấn Nhàn ( Đức said nha thầy) :)))

---

backend/src/main/java/swp391/com/backend/repository/appointments/Appointments.java
backend/src/main/java/swp391/com/backend/repository/appointments/MedicalRecord.java
backend/src/main/java/swp391/com/backend/repository/order/Order.java
backend/src/main/java/swp391/com/backend/repository/order/Result.java
backend/src/main/java/swp391/com/backend/repository/order/ResultDetail.java
backend/src/main/java/swp391/com/backend/repository/roles/Account.java
backend/src/main/java/swp391/com/backend/repository/roles/Admin.java
backend/src/main/java/swp391/com/backend/repository/roles/Staff.java
backend/src/main/java/swp391/com/backend/repository/test/Package.java
backend/src/main/java/swp391/com/backend/repository/test/PackageTest.java
backend/src/main/java/swp391/com/backend/repository/test/Test.java

Created repository package for CRUD operations of entities

repository

---

frontend/src/pages/Public/Home.tsx

Chỉnh lại giao diện homepage chưa chỉnh sửa header và thêm các chức năng

Chỉnh lại giao diện Home

---

frontend/src/components/Badge/StatusBadge.tsx
frontend/src/components/Button/NewAppointmentButton.tsx
frontend/src/components/Button/ViewResultButton.tsx
frontend/src/components/Popup/AppointmentDetailPopup.tsx
frontend/src/components/Popup/BookingSuccessPopup.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Table/AppointmentTable.tsx
frontend/src/components/TitleBar/AppointmentTitleBar.tsx
frontend/src/components/UtilityBar/AppointmentUtilityBar.tsx
frontend/src/layouts/AppLayout.tsx
frontend/src/pages/Customer/Appointments.tsx
frontend/src/pages/Customer/BookAppointmentPage.tsx
frontend/src/pages/Customer/DoctorDetailPage.tsx

Appointment

---

frontend/src/pages/Public/AboutUs.tsx
frontend/src/pages/Public/Home.tsx

Mới tạo thêm trang AboutUs và có thể vô từ trang Home qua button More about us ở đầu trang

Add AboutUs Page

---

backend/pom.xml
backend/src/main/java/swp391/com/backend/domain/controller/cycle/CycleController.java
backend/src/main/java/swp391/com/backend/domain/dto/CycleDTO.java
backend/src/main/java/swp391/com/backend/domain/dto/request/CycleCreationRequest.java
backend/src/main/java/swp391/com/backend/domain/mapper/CycleMapper.java
backend/src/main/java/swp391/com/backend/jpa/pojo/cycle/Cycle.java
backend/src/main/java/swp391/com/backend/jpa/repository/cycle/CycleRepository.java
backend/src/main/java/swp391/com/backend/jpa/repository/cycle/CycleSymptomByDateRepository.java
backend/src/main/java/swp391/com/backend/jpa/repository/cycle/SymptomRepository.java
backend/src/main/java/swp391/com/backend/service/cycle/CycleService.java

Added api for cycle entity manipulation and added swagger for api testing

Cycle api and swagger

---

frontend/src/layouts/AppLayout.tsx
frontend/src/pages/Public/ChangePassword.tsx
frontend/src/pages/Public/EnterOTP.tsx
frontend/src/pages/Public/ForgotPassword.tsx
frontend/src/pages/Public/Login.tsx

Hoàn thành trang Login và các trang chức năng forget password( bao gồm nhập gmail, otp và đăng ký lại  mật khẩu)

Login and forget Password

---

frontend/src/layouts/AppLayout.tsx
frontend/src/pages/Public/Services.tsx

Service page

---

frontend/src/components/Popup/ReminderSettingsPopup.tsx

Update 'x' for the pop up of the button 'cai dat' to exit

---

frontend/src/components/Header/PublicHeader.tsx
frontend/src/layouts/AppLayout.tsx
frontend/src/layouts/PublicLayout.tsx

- Update lại header cho những trang public page

Update header for public page

---

frontend/src/App.tsx
frontend/src/components/Header/AdminHeader.tsx
frontend/src/layouts/AppLayout.tsx
frontend/src/layouts/DoctorLayout..tsx
frontend/src/pages/Public/Login.tsx

Role-based authentication on login

Role-based access control at login

---

backend/src/main/java/swp391/com/backend/domain/controller/appointments/AppointmentsController.java
backend/src/main/java/swp391/com/backend/domain/controller/enumerators/EnumeratorController.java
backend/src/main/java/swp391/com/backend/domain/dto/dto/AppointmentDTO.java
backend/src/main/java/swp391/com/backend/domain/dto/dto/ExaminationCreateResponse.java
backend/src/main/java/swp391/com/backend/domain/dto/dto/ExaminationDTO.java
backend/src/main/java/swp391/com/backend/domain/dto/simpledto/SimpleAppointmentDTO.java
backend/src/main/java/swp391/com/backend/domain/dto/simpledto/SimpleExaminationDTO.java
backend/src/main/java/swp391/com/backend/domain/mapper/AppointmentMapper.java
backend/src/main/java/swp391/com/backend/domain/mapper/ExaminationMapper.java
backend/src/main/java/swp391/com/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/swp391/com/backend/jpa/pojo/schedule/Slot.java

Fixed slot api to only return time range

Changed slot to only return the time range

---

frontend/src/components/Header/Header.tsx

- Chỉnh sửa lại thanh header cho customer còn udate tiếp ( còn thiếu nhiều trang cần thiết)

Update header for customer

---

frontend/src/components/Badge/StatusBadge.tsx
frontend/src/pages/Staff/FormUpdateTestResult.tsx
frontend/src/pages/Staff/UpdateTestResult.tsx

Add the API to the update test result page and edit form update test result

Add the API to the update test result page

---

frontend/src/pages/Customer/STITests.tsx

Edit mapping time in Testing History

---

frontend/src/pages/Staff/FormUpdateTestResult.tsx
frontend/src/pages/Staff/UpdateTestResult.tsx

Add api staff,  and update status in form update test result.

add api staff, and update status in form test result

---

frontend/src/pages/Doctor/OnlineConsultation.tsx

Add api page online consultation

Add api page online consultation

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/PostDetailModal/PostDetailModal.tsx
frontend/src/components/Sidebar/AdminSidebar.tsx
frontend/src/layouts/AdminLayout.tsx
frontend/src/pages/Admin/AdminDashboard.tsx
frontend/src/pages/Admin/ContentManagement.tsx
frontend/src/pages/Admin/Reports.tsx

- Hoàn thành các trang còn thiếu của admin(dashboard,content-management,reports) cần update thêm

Admin page

---

frontend/src/components/Popup/DayNotePopup.tsx
frontend/src/pages/Customer/MenstrualCycles.tsx
frontend/src/pages/Customer/MenstrualCyclesAll.tsx

 "Menstrual"

---

frontend/src/pages/Admin/ApproveResult.tsx

Add button View details in page Approve Result

Add button View details in page Approve Result

---

frontend/src/App.tsx
frontend/src/AppRouter.tsx
frontend/src/components/ProfileGuard.tsx
frontend/src/components/layout/Header/AdminHeader.tsx
frontend/src/components/layout/Header/Header.tsx
frontend/src/pages/Customer/CompleteProfile.tsx
frontend/src/pages/Customer/MyProfile.tsx
frontend/src/pages/Guest/SignUp.tsx
frontend/src/routes/customerRoutes.tsx
frontend/src/styles/pages/profile.css
frontend/src/utils/auth.ts

Thêm trang profile cho customer sau khi đăng ký tài khoản có nối APi BE và có hiện avatar theo tên

update add profile customer

---

frontend/src/App.tsx
frontend/src/api/index.ts
frontend/src/api/services/blogService.ts
frontend/src/api/services/index.ts
frontend/src/components/feature/Modal/BlogFormModal.tsx
frontend/src/components/feature/Modal/CreateUserModal.tsx
frontend/src/components/feature/PostDetailModal/PostDetailModal.tsx
frontend/src/pages/Admin/Blog/Blogs.tsx
frontend/src/pages/DebugPage.tsx

Blogs management

---

frontend/src/pages/Customer/Examination/ExaminationDetail.tsx

Reverts TaiDuc1001/SWP391_Menstrual-Management#116

Revert "Demo2"

---

backend/src/main/java/swp391/com/backend/feature/panel/controller/AdminPanelController.java
frontend/src/api/services/panelService.ts
frontend/src/components/common/Dialog/ConfirmDialog.tsx
frontend/src/components/feature/Modal/PanelModal.tsx
frontend/src/components/feature/Modal/TestTypeModal.tsx
frontend/src/pages/Admin/TestPanel/TestPanels.tsx

Fix service management

---

frontend/src/components/feature/Modal/CreateUserModal.tsx
frontend/src/components/feature/Modal/UpdateUserModal.tsx

Fix account page for admin

---

frontend/src/pages/Customer/Examination/ExaminationDetail.tsx

Add book Appointment for AI

---

frontend/src/components/layout/Layouts/PublicLayout.tsx
frontend/src/pages/AboutUs.tsx
frontend/src/pages/AboutUs_new.tsx
frontend/src/pages/Blogs.tsx
frontend/src/pages/Contact.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Services.tsx
frontend/src/pages/Services_new.tsx

chỉnh lại giao diện guest cho đẹp hơn

update style for guest

---

backend/src/main/java/swp391/com/backend/feature/appointment/controller/RescheduleController.java
backend/src/main/java/swp391/com/backend/feature/appointment/data/RescheduleOption.java
backend/src/main/java/swp391/com/backend/feature/appointment/data/RescheduleOptionRepository.java
backend/src/main/java/swp391/com/backend/feature/appointment/data/RescheduleRequest.java
backend/src/main/java/swp391/com/backend/feature/appointment/data/RescheduleRequestRepository.java
backend/src/main/java/swp391/com/backend/feature/appointment/dto/CreateRescheduleRequestDTO.java
backend/src/main/java/swp391/com/backend/feature/appointment/dto/RescheduleRequestDTO.java
backend/src/main/java/swp391/com/backend/feature/appointment/dto/RescheduleStatus.java
backend/src/main/java/swp391/com/backend/feature/appointment/mapper/RescheduleMapper.java
backend/src/main/java/swp391/com/backend/feature/appointment/service/RescheduleService.java
backend/src/main/resources/sql/05_reschedule.sql
frontend/src/api/services/rescheduleService.ts
frontend/src/components/feature/Card/RescheduleStatusCard.tsx
frontend/src/components/feature/Modal/RescheduleModal.tsx
frontend/src/components/feature/Notification/ErrorNotification.tsx
frontend/src/components/feature/Notification/SuccessNotification.tsx
frontend/src/components/feature/Table/Customer/Appointments.tsx
frontend/src/pages/Customer/Appointment/AppointmentDetail.tsx
frontend/src/pages/Customer/Appointment/RescheduleHistory.tsx
frontend/src/pages/Doctor/Reschedule/RescheduleRequests.tsx
frontend/src/routes/customerRoutes.tsx
frontend/src/routes/doctorRoutes.tsx
frontend/src/styles/index.css
frontend/src/styles/pages/appointment-detail.css

add reschedule

---

backend/src/main/java/swp391/com/backend/feature/appointment/controller/AppointmentsController.java
backend/src/main/java/swp391/com/backend/feature/appointment/controller/RescheduleController.java
backend/src/main/java/swp391/com/backend/feature/appointment/data/AppointmentRepository.java
backend/src/main/java/swp391/com/backend/feature/appointment/dto/AppointmentDTO.java
backend/src/main/java/swp391/com/backend/feature/appointment/dto/RatingRequest.java
backend/src/main/java/swp391/com/backend/feature/appointment/service/AppointmentsService.java
backend/src/main/java/swp391/com/backend/feature/appointment/service/RescheduleService.java
frontend/src/components/feature/Modal/RatingModal.tsx
frontend/src/components/feature/Modal/RescheduleModal.tsx
frontend/src/components/feature/Rating/Rating.tsx
frontend/src/components/feature/Table/Customer/Appointments.tsx
frontend/src/pages/Customer/Appointment/AppointmentBooking.tsx
frontend/src/pages/Customer/Appointment/AppointmentDetail.tsx
frontend/src/pages/Customer/Dashboard.tsx
frontend/src/pages/Doctor/Appointment/Appointments.tsx
frontend/src/styles/pages/appointment-detail.css

Thêm chức năng đánh giá bác sĩ

add rating

---

frontend/src/api/services/staffDashboardService.ts
frontend/src/pages/Staff/Dashboard.tsx

Thêm trand dashboad cho staff có kết nối API

add dashboad staff connect API BE

---

frontend/src/pages/Doctor/Dashboard.tsx

fix bug doctor dashboad

---

frontend/src/api/hooks/useTableState.ts
frontend/src/pages/Customer/Appointment/Appointments.tsx
frontend/src/pages/Customer/Examination/Examinations.tsx

fix lỗi booking mới nhất lên trước

 fix booking

---

backend/src/main/java/swp391/com/backend/feature/account/controller/AccountController.java
backend/src/main/java/swp391/com/backend/feature/account/dto/request/AdminAccountCreateRequest.java
backend/src/main/java/swp391/com/backend/feature/account/dto/request/AdminAccountUpdateRequest.java
backend/src/main/java/swp391/com/backend/feature/account/service/AccountService.java
backend/src/main/java/swp391/com/backend/feature/doctor/controller/DoctorController.java
backend/src/main/java/swp391/com/backend/feature/doctor/service/DoctorService.java
frontend/src/api/services/accountService.ts
frontend/src/api/services/doctorService.ts
frontend/src/components/feature/Modal/CreateUserModal.tsx
frontend/src/components/feature/Modal/EditDoctorProfileModal.tsx
frontend/src/components/feature/Modal/UpdateUserModal.tsx
frontend/src/components/feature/Modal/UserDetailModal.tsx
frontend/src/constants/doctorProfile.ts
frontend/src/pages/Admin/Account/Accounts.tsx

Update account page

---

backend/src/main/java/swp391/com/backend/feature/schedule/controller/ScheduleController.java
backend/src/main/java/swp391/com/backend/feature/schedule/data/ScheduleRepository.java
backend/src/main/java/swp391/com/backend/feature/schedule/data/Slot.java
backend/src/main/java/swp391/com/backend/feature/schedule/dto/CreateScheduleRequest.java
backend/src/main/java/swp391/com/backend/feature/schedule/dto/DoctorScheduleResponse.java
backend/src/main/java/swp391/com/backend/feature/schedule/dto/ScheduleResponse.java
backend/src/main/java/swp391/com/backend/feature/schedule/dto/SlotOptionResponse.java
backend/src/main/java/swp391/com/backend/feature/schedule/dto/SlotResponse.java
backend/src/main/java/swp391/com/backend/feature/schedule/dto/UpdateScheduleRequest.java
backend/src/main/java/swp391/com/backend/feature/schedule/mapper/ScheduleMapper.java
backend/src/main/java/swp391/com/backend/feature/schedule/service/ScheduleService.java
frontend/src/api/services/index.ts
frontend/src/api/services/scheduleService.ts
frontend/src/components/feature/Modal/CreateScheduleModal.tsx
frontend/src/components/feature/Modal/DeleteConfirmModal.tsx
frontend/src/components/feature/Modal/UpdateScheduleModal.tsx
frontend/src/components/feature/Modal/ViewScheduleModal.tsx
frontend/src/pages/Admin/WorkSchedule/WorkScheduleManagement.tsx
frontend/src/routes/adminRoutes.tsx

feat(schedule): add admin feature to manage doctor working schedules with paging and improved UI

Manage work schedules
